# Jas Swift Application
#
# The Swift app is built using Swift Package Manager.
#
# Build: swift build
# Run: swift run Jas
# Test: swift test
#
# For Bazel testing, use: bazel run //JasSwift:run_tests
#
# Documentation:
# - See Package.swift for the package definition
# - Sources/ contains the Swift source code
# - Tests/ contains the test suite

exports_files(
    glob(["**/*"]),
    exclude = [
        ".build/**",
        ".swiftpm/**",
    ],
)
