#ifndef JAS_FFI_H
#define JAS_FFI_H

/* GENERATED by cbindgen from src/ffi.rs -- do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Vertex coincidence and zero-length tolerance, in input units.
 */
#define VERT_EPS 1e-9

/**
 * Parameter-band epsilon: |s| <= PARAM_EPS means "at the start".
 */
#define PARAM_EPS 1e-9

/**
 * Determinant tolerance for parallel-pair detection.
 */
#define DENOM_EPS 1e-12

/**
 * Perpendicular-distance tolerance for collinearity of a parallel
 * pair, in input units.
 */
#define COLLINEAR_EPS 1e-9

/**
 * Gap between marker and text per PARAGRAPH.md §Marker rendering.
 * Stored on each ParagraphSegment so future variants (e.g. wider
 * markers like "iii.") could override the constant per item.
 */
#define MARKER_GAP_PT 12.0

/**
 * Segments per cap semicircle when the renderer flattens one.
 *
 * The chord error of an `n`-segment semicircle is `r * (1 - cos(pi/(2n)))`;
 * at 32 that is `r * 0.0012`, i.e. 0.006pt for a 10pt-wide stroke and 0.12pt
 * for a 200pt one. Both ports use this same number, and it travels on the
 * algorithm wire as `default_arc_steps` so it cannot drift between them.
 */
#define CAP_ARC_STEPS 32

/**
 * Penalty value above which a candidate is treated as "forbidden"
 * (never broken at). Matches Knuth's INFINITY threshold.
 */
#define PENALTY_INFINITY 10000.0

#define CHAR_WIDTH 10

/**
 * Pointer-to-geometry hit tolerance, in document units.
 */
#define HIT_RADIUS 8.0

/**
 * Edge length of a drawn selection handle, in document units.
 */
#define HANDLE_DRAW_SIZE 10.0

/**
 * Pointer travel before a press becomes a drag, in document units.
 */
#define DRAG_THRESHOLD 4.0

/**
 * Offset applied to a pasted or duplicated element, in document units.
 */
#define PASTE_OFFSET 24.0

/**
 * Default side count for the polygon tool.
 */
#define POLYGON_SIDES 5

/**
 * Default eraser radius, in document units.
 */
#define ERASER_SIZE 2.0

/**
 * Default smooth-tool strength.
 */
#define SMOOTH_SIZE 100.0

/**
 * How many draws one collision-free id gets before the mint is reported
 * failed. 100 — the value every open-coded copy of this loop used before
 * [`mint_unique_ids`] absorbed them; Swift's `idMintRetryBudget` holds the
 * same number so the ports cannot drift on give-up behaviour.
 */
#define ID_MINT_RETRY_BUDGET 100

#define VERSION 2

#define MIN_VERSION 2

/**
 * Line segments per Bezier curve when flattening paths.
 */
#define FLATTEN_STEPS 20

/**
 * Average character width as a fraction of font size.
 */
#define APPROX_CHAR_WIDTH_FACTOR 0.6

/**
 * Ratio of inner radius to outer radius for the default star.
 */
#define STAR_INNER_RATIO 0.4

/**
 * The DPI every headless target is pinned to. See the module note: DIPs are
 * CSS pixels only here.
 */
#define PINNED_DPI 96.0

/**
 * Cursor blink half-period in milliseconds (matches the macOS default).
 * Shared by [`crate::tools::type_tool`] and [`crate::tools::type_on_path_tool`].
 */
#define BLINK_HALF_PERIOD_MS 530.0

#define MIN_TOOLBAR_WIDTH 72.0

#define MIN_TOOLBAR_HEIGHT 200.0

#define MIN_CANVAS_HEIGHT 200.0

#define MIN_PANE_DOCK_WIDTH 150.0

#define MIN_PANE_DOCK_HEIGHT 100.0

#define DEFAULT_TOOLBAR_WIDTH 72.0

#define BORDER_HIT_TOLERANCE 6.0

#define MIN_PANE_VISIBLE 50.0

#define MIN_DOCK_WIDTH 150.0

#define MAX_DOCK_WIDTH 500.0

#define MIN_GROUP_HEIGHT 40.0

#define MIN_CANVAS_WIDTH 200.0

#define DEFAULT_DOCK_WIDTH 240.0

#define DEFAULT_FLOATING_WIDTH 220.0

#define SNAP_DISTANCE 20.0

/**
 * Current layout format version. Saved layouts with a different version
 * are rejected and replaced with the default layout.
 */
#define LAYOUT_VERSION 3

/**
 * Status codes. **1-5 map one-to-one and BY POSITION onto the five frozen
 * `OpError` classes** (`document/op_apply.rs`, ratified OP_LOG.md §13). Codes
 * >= 100 are TRANSPORT faults that cannot arise from `op_apply`, kept in a
 * disjoint range so this ABI can never be mistaken for having widened a
 * ratified taxonomy: anything 1-5 is a core verdict, anything >= 100 never
 * reached the core.
 */
enum JasStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JasStatus_Ok = 0,
  JasStatus_MalformedEnvelope = 1,
  JasStatus_UnknownVerb = 2,
  JasStatus_MissingParam = 3,
  JasStatus_BadParamType = 4,
  JasStatus_MissingTarget = 5,
  JasStatus_BadUtf8 = 100,
  JasStatus_BadJson = 101,
  JasStatus_NullHandle = 102,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JasStatus JasStatus;
#else
typedef int32_t JasStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * One document session. Deliberately NOT `Send`/`Sync`: `RefCell` and the
 * `Rc`-based model make single-thread use a type-level fact on the Rust side
 * even though the C ABI cannot carry it (BL2).
 */
typedef struct JasEngine JasEngine;

/**
 * Which fill rule reads a [`PolygonSet`]'s rings — the thing the
 * algorithm layer must carry rather than assume. Mirrors SVG/PDF
 * `fill-rule` and `crate::geometry::element::FillRule`, which is the
 * document-side spelling of the same choice.
 */
typedef struct PolyFillRule PolyFillRule;

/**
 * SVG transform as a 2D affine matrix [a b c d e f].
 *
 * Represents the matrix:
 *     | a c e |
 *     | b d f |
 *     | 0 0 1 |
 */
typedef struct Transform Transform;

/**
 * An owned UTF-8 byte span handed to the caller. **Rust owns it** (BL4):
 * copy immediately, then release with [`jas_free`].
 *
 * `ptr == NULL && len == 0` is the canonical empty result and is safe to free.
 */
typedef struct JasBytes {
  const uint8_t *ptr;
  uintptr_t len;
} JasBytes;









#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create one document session. Returns NULL only on allocation failure.
 *
 * **BL2**: every subsequent call for this engine must be on this thread.
 */
struct JasEngine *jas_engine_new(void);

/**
 * Destroy an engine. Idempotent on NULL.
 *
 * # Safety
 * `e` must be a pointer from [`jas_engine_new`] that has not already been freed.
 */
void jas_engine_free(struct JasEngine *e);

/**
 * Release a span returned by this ABI (BL4). Safe on the empty `JasBytes`.
 *
 * # Safety
 * `b` must be a value returned by this ABI and not already freed.
 */
void jas_free(struct JasBytes b);

/**
 * Build identity, for the shell to log and for the harness to prove it is
 * talking to the library it thinks it is.
 */
struct JasBytes jas_version(void);

/**
 * The session's document as canonical test JSON — the SAME bytes the
 * cross-language corpus compares (BL6: a summary, not geometry).
 *
 * # Safety
 * `e` must be a live engine pointer.
 */
struct JasBytes jas_document_json(struct JasEngine *e);

/**
 * Apply one op envelope (BL1: the shell sends events, never state; BL6: the
 * journal's resolved-literal vocabulary, which was built for replay and is
 * therefore already an IPC vocabulary).
 *
 * Returns [`JasStatus::Ok`] or the frozen class of the rejection. Detail via
 * [`jas_last_error_json`].
 *
 * # Safety
 * `op_json` must be NULL or valid for `len` bytes.
 */
JasStatus jas_dispatch_event(struct JasEngine *e, const uint8_t *op_json, uintptr_t len);

/**
 * Detail for the last rejection: `{"class":"...", "name"|"id":"..."}` with the
 * class spelled as the negative fixtures spell it. Empty when the last call
 * succeeded.
 *
 * # Safety
 * `e` must be a live engine pointer.
 */
struct JasBytes jas_last_error_json(struct JasEngine *e);

/**
 * The structural widget tree for a panel, canonically serialised.
 *
 * This makes the IDENTICAL call the corpus driver makes at
 * `cross_language_test.rs:5317` — `widget_tree(&bundle["panels"][id], ctx)` —
 * which is what lets S-A gate (ii) be a byte-identical round-trip against
 * `test_fixtures/algorithms/panel_widget_tree.json` rather than a
 * self-consistency check.
 *
 * # Safety
 * Both spans must be NULL or valid for their stated lengths.
 */
struct JasBytes jas_widget_tree(struct JasEngine *e,
                                const uint8_t *panel_id,
                                uintptr_t panel_len,
                                const uint8_t *ctx_json,
                                uintptr_t ctx_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* JAS_FFI_H */
