#ifndef JAS_FFI_H
#define JAS_FFI_H

/* GENERATED by cbindgen from src/ffi.rs -- do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Vertex coincidence and zero-length tolerance, in input units.
 */
#define VERT_EPS 1e-9

/**
 * Parameter-band epsilon: |s| <= PARAM_EPS means "at the start".
 */
#define PARAM_EPS 1e-9

/**
 * Determinant tolerance for parallel-pair detection.
 */
#define DENOM_EPS 1e-12

/**
 * Perpendicular-distance tolerance for collinearity of a parallel
 * pair, in input units.
 */
#define COLLINEAR_EPS 1e-9

/**
 * Gap between marker and text per PARAGRAPH.md §Marker rendering.
 * Stored on each ParagraphSegment so future variants (e.g. wider
 * markers like "iii.") could override the constant per item.
 */
#define MARKER_GAP_PT 12.0

/**
 * Segments per cap semicircle when the renderer flattens one.
 *
 * The chord error of an `n`-segment semicircle is `r * (1 - cos(pi/(2n)))`;
 * at 32 that is `r * 0.0012`, i.e. 0.006pt for a 10pt-wide stroke and 0.12pt
 * for a 200pt one. Both ports use this same number, and it travels on the
 * algorithm wire as `default_arc_steps` so it cannot drift between them.
 */
#define CAP_ARC_STEPS 32

/**
 * Penalty value above which a candidate is treated as "forbidden"
 * (never broken at). Matches Knuth's INFINITY threshold.
 */
#define PENALTY_INFINITY 10000.0

#define CHAR_WIDTH 10

/**
 * Pointer-to-geometry hit tolerance, in document units.
 */
#define HIT_RADIUS 8.0

/**
 * Edge length of a drawn selection handle, in document units.
 */
#define HANDLE_DRAW_SIZE 10.0

/**
 * Pointer travel before a press becomes a drag, in document units.
 */
#define DRAG_THRESHOLD 4.0

/**
 * Offset applied to a pasted or duplicated element, in document units.
 */
#define PASTE_OFFSET 24.0

/**
 * Default side count for the polygon tool.
 */
#define POLYGON_SIDES 5

/**
 * Default eraser radius, in document units.
 */
#define ERASER_SIZE 2.0

/**
 * Default smooth-tool strength.
 */
#define SMOOTH_SIZE 100.0

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * Status codes for the spike seam. Deliberately NOT `JasStatus`: that enum is
 * the frozen five-class contract of the S-A surface, and widening a frozen
 * vocabulary for a spike is how a spike becomes load-bearing by accident.
 */
#define JAS_PAINT_OK 0
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * Caller passed NULL. POSITIVE so it cannot collide with an HRESULT.
 */
#define JAS_PAINT_NULL_SURFACE 1
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * The pointer was not a usable `IDXGISurface`. Positive, same reason.
 */
#define JAS_PAINT_NOT_A_SURFACE 2
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * The two surfaces disagree on size or format, so the copy would be DROPPED.
 * Positive, same reason.
 *
 * EXISTS BECAUSE THE FAILURE IT NAMES IS OTHERWISE SILENT. `CopyResource`
 * returns `void`; D3D11 drops a mismatched copy rather than faulting; and the
 * debug layer that would report the drop is unavailable on this box (Graphics
 * Tools is not installed). Without this code the seam returns `JAS_PAINT_OK`
 * and the host presents a stale frame -- a status truthful about the wrong
 * thing. See `d3d11_silently_drops_a_size_mismatched_copy_...` for the
 * measurement, driven rather than cited.
 */
#define JAS_PAINT_SIZE_MISMATCH 3
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * The two surfaces belong to DIFFERENT D3D11 devices. Positive, same reason.
 *
 * THIS ONE IS NOT ABOUT SILENCE - IT IS ABOUT ATTRIBUTION. Unlike a size
 * mismatch, which D3D11 drops quietly, a cross-device `CopyResource` REMOVES the
 * destination's device: measured on WARP, `GetDeviceRemovedReason` goes to
 * `0x887A0020` (`DXGI_ERROR_DRIVER_INTERNAL_ERROR`) while the source's device
 * stays healthy. Everything created on the dead device fails afterwards, several
 * calls away from the cause.
 *
 * `DRIVER_INTERNAL_ERROR` is exactly the error that gets blamed on hardware or a
 * driver. Refusing here is the difference between a bug report about the GPU and
 * one about a half-finished device-lost recovery.
 */
#define JAS_PAINT_DEVICE_MISMATCH 4
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * The scene bytes were not valid UTF-8 JSON, or not a JSON array of commands.
 * Positive, same reason as the sentinels above.
 */
#define JAS_PAINT_BAD_SCENE 5
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * The scene was decoded and replayed, but the painter could not draw every
 * command in it.
 *
 * ⛔ THIS IS A REFUSAL, NOT A WARNING, AND THAT IS THE WHOLE POINT. A replay
 * that silently drops the commands it does not understand paints a PARTIAL
 * document and returns OK -- the host then presents a frame that is missing
 * artwork with nothing anywhere reporting it. That is the same class as the
 * dropped `CopyResource` above: a status truthful about the wrong thing. The
 * seam refuses instead, and `ReplayReport::unsupported` is the work list.
 */
#define JAS_PAINT_SCENE_INCOMPLETE 6
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * Reserved by the RED half of this increment; no shipped path returns it.
 */
#define JAS_PAINT_NOT_IMPLEMENTED 7
#endif

/**
 * How many draws one collision-free id gets before the mint is reported
 * failed. 100 — the value every open-coded copy of this loop used before
 * [`mint_unique_ids`] absorbed them; Swift's `idMintRetryBudget` holds the
 * same number so the ports cannot drift on give-up behaviour.
 */
#define ID_MINT_RETRY_BUDGET 100

#define VERSION 2

#define MIN_VERSION 2

/**
 * Line segments per Bezier curve when flattening paths.
 */
#define FLATTEN_STEPS 20

/**
 * Average character width as a fraction of font size.
 */
#define APPROX_CHAR_WIDTH_FACTOR 0.6

/**
 * Ratio of inner radius to outer radius for the default star.
 */
#define STAR_INNER_RATIO 0.4

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * The DPI every headless target is pinned to. See the module note: DIPs are
 * CSS pixels only here.
 */
#define PINNED_DPI 96.0
#endif

/**
 * Cursor blink half-period in milliseconds (matches the macOS default).
 * Shared by [`crate::tools::type_tool`] and [`crate::tools::type_on_path_tool`].
 */
#define BLINK_HALF_PERIOD_MS 530.0

#define MIN_TOOLBAR_WIDTH 72.0

#define MIN_TOOLBAR_HEIGHT 200.0

#define MIN_CANVAS_HEIGHT 200.0

#define MIN_PANE_DOCK_WIDTH 150.0

#define MIN_PANE_DOCK_HEIGHT 100.0

#define DEFAULT_TOOLBAR_WIDTH 72.0

#define BORDER_HIT_TOLERANCE 6.0

#define MIN_PANE_VISIBLE 50.0

#define MIN_DOCK_WIDTH 150.0

#define MAX_DOCK_WIDTH 500.0

#define MIN_GROUP_HEIGHT 40.0

#define MIN_CANVAS_WIDTH 200.0

#define DEFAULT_DOCK_WIDTH 240.0

#define DEFAULT_FLOATING_WIDTH 220.0

#define SNAP_DISTANCE 20.0

/**
 * Current layout format version. Saved layouts with a different version
 * are rejected and replaced with the default layout.
 */
#define LAYOUT_VERSION 3

/**
 * Status codes. **1-5 map one-to-one and BY POSITION onto the five frozen
 * `OpError` classes** (`document/op_apply.rs`, ratified OP_LOG.md §13). Codes
 * >= 100 are TRANSPORT faults that cannot arise from `op_apply`, kept in a
 * disjoint range so this ABI can never be mistaken for having widened a
 * ratified taxonomy: anything 1-5 is a core verdict, anything >= 100 never
 * reached the core.
 */
enum JasStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  JasStatus_Ok = 0,
  JasStatus_MalformedEnvelope = 1,
  JasStatus_UnknownVerb = 2,
  JasStatus_MissingParam = 3,
  JasStatus_BadParamType = 4,
  JasStatus_MissingTarget = 5,
  JasStatus_BadUtf8 = 100,
  JasStatus_BadJson = 101,
  JasStatus_NullHandle = 102,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum JasStatus JasStatus;
#else
typedef int32_t JasStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * One document session. Deliberately NOT `Send`/`Sync`: `RefCell` and the
 * `Rc`-based model make single-thread use a type-level fact on the Rust side
 * even though the C ABI cannot carry it (BL2).
 */
typedef struct JasEngine JasEngine;

/**
 * Which fill rule reads a [`PolygonSet`]'s rings — the thing the
 * algorithm layer must carry rather than assume. Mirrors SVG/PDF
 * `fill-rule` and `crate::geometry::element::FillRule`, which is the
 * document-side spelling of the same choice.
 */
typedef struct PolyFillRule PolyFillRule;

/**
 * SVG transform as a 2D affine matrix [a b c d e f].
 *
 * Represents the matrix:
 *     | a c e |
 *     | b d f |
 *     | 0 0 1 |
 */
typedef struct Transform Transform;

/**
 * An owned UTF-8 byte span handed to the caller. **Rust owns it** (BL4):
 * copy immediately, then release with [`jas_free`].
 *
 * `ptr == NULL && len == 0` is the canonical empty result and is safe to free.
 */
typedef struct JasBytes {
  const uint8_t *ptr;
  uintptr_t len;
} JasBytes;









#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create one document session. Returns NULL only on allocation failure.
 *
 * **BL2**: every subsequent call for this engine must be on this thread.
 */
struct JasEngine *jas_engine_new(void);

/**
 * Destroy an engine. Idempotent on NULL.
 *
 * # Safety
 * `e` must be a pointer from [`jas_engine_new`] that has not already been freed.
 */
void jas_engine_free(struct JasEngine *e);

/**
 * Release a span returned by this ABI (BL4). Safe on the empty `JasBytes`.
 *
 * # Safety
 * `b` must be a value returned by this ABI and not already freed.
 */
void jas_free(struct JasBytes b);

/**
 * Build identity, for the shell to log and for the harness to prove it is
 * talking to the library it thinks it is.
 */
struct JasBytes jas_version(void);

/**
 * The session's document as canonical test JSON — the SAME bytes the
 * cross-language corpus compares (BL6: a summary, not geometry).
 *
 * # Safety
 * `e` must be a live engine pointer.
 */
struct JasBytes jas_document_json(struct JasEngine *e);

/**
 * The panel's resolved bind VALUES — the ninth materializer function.
 *
 * `jas_widget_tree` is **value-blind by design**: it records the sorted KEY
 * NAMES of `bind`/`style`, which is what makes it stable across ports. So a
 * shell built on the surface without this one materializes native controls with
 * nothing in them. This returns the third pass — `interpreter::bind_values` —
 * against a scope the ENGINE assembles.
 *
 * **It also ENROLS the panel** (S-C.2): reading a panel's values is what tells
 * the engine the shell has it open, so subsequent ticks know to keep it in
 * sync. Enrolment is a side effect of a call the shell already had to make —
 * an explicit `jas_panel_open` would have spent a boundary function to say
 * something the engine can already see.
 *
 * # Safety
 * `panel_id` must be NULL or valid for `len` bytes.
 */
struct JasBytes jas_bind_values(struct JasEngine *e, const uint8_t *panel_id, uintptr_t len);

/**
 * **The colour tick.** One control's new value in; every bind row that MOVED,
 * across every open panel, out.
 *
 * # The protocol, and what it is for
 *
 * This is the S-C.2 sync protocol, and the whole of C2 is measured on it. Its
 * shape is three decisions, each of which the gate can see the consequence of:
 *
 * 1. **The reply carries the delta**, so a tick is ONE crossing plus its
 *    `jas_free` — **two**, where a dispatch-then-fetch protocol is three (a
 *    fetch is two crossings under Rust-owns-it, BL4). The gate's derived floor
 *    assumed the two were separate calls; folding them is why this comes in
 *    under it.
 * 2. **Only rows that CHANGED are sent.** The trivial alternative is to re-read
 *    the panel whole, which is 7,038 bytes on the colour panel and is where
 *    gate ③'s ceiling comes from.
 * 3. ⭐ **Every OPEN panel is re-resolved, not just the edited one.** Refreshing
 *    only the edited panel is cheaper and is WRONG in general — a colour change
 *    with a selection moves what other panels display. The cost of being right
 *    lands on the ENGINE, not the boundary: crossings and bytes stay flat while
 *    `engine.rows_evaluated` grows with the document. That number is in the
 *    counter dump because gate ⑤ requires it and because nothing else would
 *    show it.
 *
 * # The event, and why it names a WIDGET
 *
 * `{"widget":"cp_h","key":"bind.value","value":210}` — the shell reports what
 * the user did to a CONTROL. The engine reads that widget's `bind.value` out of
 * the panel spec (`"panel.h"`) and applies it. **So the shell knows nothing
 * about colour**: no channel names, no conversion, no mode. A shell that sent
 * `{"h":210}` would be naming the engine's model, and one that sent a hex
 * would be doing the arithmetic. `key` defaults to `bind.value`.
 *
 * Returns the changed rows, each tagged with its `panel`. An empty array is a
 * well-formed answer meaning *nothing moved* — and is exactly what gate ④
 * exists to stop being read as a cheap tick, so [`jas_last_error_json`] carries
 * the outcome class when the array is empty.
 *
 * # Safety
 * Both spans must be NULL or valid for their stated lengths.
 */
struct JasBytes jas_panel_event(struct JasEngine *e,
                                const uint8_t *panel_id,
                                uintptr_t panel_len,
                                const uint8_t *event_json,
                                uintptr_t event_len);

/**
 * Zero every boundary counter. Call at the START of a named interaction so the
 * dump that follows describes that interaction alone.
 */
void jas_instr_reset(void);

/**
 * The counter dump as JSON: per-function rows plus totals, naming the surface
 * it was measured against.
 *
 * **BL4**: the span is Rust-owned. Copy it, then release with [`jas_free`].
 * Releasing it does call `jas_free`, which IS a counted crossing -- so dump
 * LAST in an interaction, or reset after freeing, or the free will appear in
 * the next reading.
 */
struct JasBytes jas_instr_counters_json(void);

/**
 * Apply one op envelope (BL1: the shell sends events, never state; BL6: the
 * journal's resolved-literal vocabulary, which was built for replay and is
 * therefore already an IPC vocabulary).
 *
 * Returns [`JasStatus::Ok`] or the frozen class of the rejection. Detail via
 * [`jas_last_error_json`].
 *
 * # Safety
 * `op_json` must be NULL or valid for `len` bytes.
 */
JasStatus jas_dispatch_event(struct JasEngine *e, const uint8_t *op_json, uintptr_t len);

/**
 * Detail for the last rejection: `{"class":"...", "name"|"id":"..."}` with the
 * class spelled as the negative fixtures spell it. Empty when the last call
 * succeeded.
 *
 * # Safety
 * `e` must be a live engine pointer.
 */
struct JasBytes jas_last_error_json(struct JasEngine *e);

/**
 * The structural widget tree for a panel, canonically serialised.
 *
 * This makes the IDENTICAL call the corpus driver makes at
 * `cross_language_test.rs:5317` — `widget_tree(&bundle["panels"][id], ctx)` —
 * which is what lets S-A gate (ii) be a byte-identical round-trip against
 * `test_fixtures/algorithms/panel_widget_tree.json` rather than a
 * self-consistency check.
 *
 * # ⚠️ A NULL ctx means "engine, assemble it"; an EMPTY ctx means "empty"
 *
 * The two are different on purpose, and the distinction is load-bearing:
 *
 * * **`ctx_len == 0`** — the production call. The engine assembles the scope
 *   itself, exactly as [`jas_bind_values`] does. **BL1**: a shell that had to
 *   supply `active_document.artboards` to see a data-driven panel's rows would
 *   be holding app state in C#.
 * * **`"{}"`, two bytes** — an explicit empty scope. This is what the corpus
 *   driver passes for panels whose fixtures declare no ctx, and it is why
 *   S-A gate (ii) is unaffected by the paragraph above: **no fixture passes
 *   NULL.**
 *
 * Before S-C.2 a NULL ctx meant an empty scope, and a data-driven panel
 * therefore reported its STATIC size at every document size — the second arm of
 * gate ② would have been identical to the first, measured with the widget count
 * held constant. The `bind_values` half was fixed by route (a); this is the
 * same fix on the half that reports the structure.
 *
 * # Safety
 * Both spans must be NULL or valid for their stated lengths.
 */
struct JasBytes jas_widget_tree(struct JasEngine *e,
                                const uint8_t *panel_id,
                                uintptr_t panel_len,
                                const uint8_t *ctx_json,
                                uintptr_t ctx_len);

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * Paint the S-B probe pattern into a caller-owned DXGI surface.
 *
 * Returns `JAS_PAINT_OK` (0), a positive sentinel for a bad pointer, or the
 * raw HRESULT of whichever COM call failed. The host presents; this does not.
 *
 * # Safety
 * `surface` must be NULL or a valid `IDXGISurface` COM pointer that stays
 * alive for the duration of the call. Ownership is NOT transferred: the caller
 * still releases it.
 */
int32_t jas_paint_probe_surface(void *surface, float width, float height);
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * Paint an OFFSCREEN surface, then GPU-copy it into the host's back buffer.
 *
 * The route the direct path cannot currently take. `jas_paint_probe_surface`
 * paints the back buffer itself and the host's subsequent `Present` fails with
 * `E_NOINTERFACE`; here Direct2D never touches the back buffer at all, so if
 * `Present` succeeds afterwards it confirms the mechanism by sidestepping it.
 *
 * THE COPY LIVES HERE RATHER THAN IN THE HOST, and not for tidiness. C#'s
 * `ID3D11DeviceContext::CopyResource` threw `InvalidCastException` out of
 * `InterfaceMarshaler.ConvertToNative` even with both arguments already typed
 * as `ID3D11Resource` -- a CLR marshalling wrinkle around the generated
 * interop. windows-rs calls COM directly with no marshaller in between.
 *
 * Ownership is unchanged: BOTH surfaces are the host's, borrowed for the call.
 *
 * # Safety
 * Both pointers must be NULL or valid `IDXGISurface` COM pointers alive for the
 * duration of the call. Neither is released here.
 */
int32_t jas_paint_probe_offscreen(void *back, void *offscreen, float width, float height);
#endif

#if (defined(JAS_WITH_D2D) && defined(_WIN32))
/**
 * Paint a RECORDED DISPLAY LIST into a caller-owned DXGI surface.
 *
 * ⭐ THE NODE THIS WHOLE LANE WAS MISSING. `jas_paint_probe_surface` above
 * draws a centred square -- a fixed pattern that proves the SEAM and says
 * nothing about the document. `Direct2DPainter` (1,163 lines) can draw a real
 * recorded scene, and `SurfaceTarget` can wrap the buffer the host presents.
 * Measured 2026-08-31: `SurfaceTarget` was referenced by this file and its own
 * module and NOWHERE ELSE, and every `Direct2DPainter` test drove a
 * `HeadlessTarget` (a WIC bitmap) instead. **Two proven halves that had never
 * been joined** -- so no jas artwork had ever reached the surface a window
 * presents, on any run, ever.
 *
 * # Safety
 * `surface` must be NULL or a valid `IDXGISurface` that outlives the call;
 * ownership is not transferred. `scene` must be NULL or point to `len` readable
 * bytes.
 */
int32_t jas_paint_scene(void *surface,
                        const uint8_t *scene,
                        uintptr_t len,
                        float width,
                        float height);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* JAS_FFI_H */
