import Foundation
import Testing
@testable import JasLib

// The widget event corpus through Swift's headless `WidgetEvent`.
//
// `test_fixtures/widget_events/corpus.json` is GENERATED by the reference
// (`workspace_interpreter/widget_event.py`, `WIDGET_EVENTS.md`). The store
// is seeded as the corpus says a consumer rebuilds it: the bundle's `state`
// defaults, then `before.state`; the widget's panel scope is `before.panel`,
// whole, and that panel is the active panel.
//
// ⛔ STRONGER THAN THE ENGINE'S ARM, ON PURPOSE. The engine's door reports
// no `behaviors_run` or `bind_written`, so `ffi.rs` compares the refusal
// class, the panel scope and the changed globals. This module returns the
// whole result, so ALL of `expected.result` is compared too: outcome,
// reason, value, bind_written and behaviors_run.

/// Fixture-relative, the shape `scripts/check_corpus_manifest.py` reads as
/// Swift's claim on the family (the engine's arm uses the same form).
private let widgetEventCorpus = "widget_events/corpus.json"

private func corpusCases() -> [[String: Any]] {
    let testsDir = ((#filePath as NSString).deletingLastPathComponent as NSString)
        .deletingLastPathComponent
    let fixtures = (testsDir as NSString).appendingPathComponent("../../test_fixtures")
    let path = ((fixtures as NSString).appendingPathComponent(widgetEventCorpus) as NSString)
        .standardizingPath
    guard let data = FileManager.default.contents(atPath: path),
          let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let cases = root["cases"] as? [[String: Any]] else {
        Issue.record("the widget event corpus did not load from \(path)")
        return []
    }
    return cases
}

/// Numbers as numbers, a JSON boolean as a boolean (never as 0 or 1), a
/// JSON null and a missing value as the same null, recursively.
private func sameJson(_ a: Any?, _ b: Any?) -> Bool {
    let a = a is NSNull ? nil : a
    let b = b is NSNull ? nil : b
    switch (a, b) {
    case (nil, nil):
        return true
    case let (x as [String: Any], y as [String: Any]):
        return x.count == y.count
            && x.allSatisfy { k, v in y.keys.contains(k) && sameJson(v, y[k]) }
    case let (x as [Any], y as [Any]):
        return x.count == y.count && zip(x, y).allSatisfy { sameJson($0, $1) }
    case let (x?, y?):
        return Value.fromJson(x) == Value.fromJson(y)
    default:
        return false
    }
}

private func show(_ v: Any?) -> String {
    guard let v = v, !(v is NSNull) else { return "null" }
    if JSONSerialization.isValidJSONObject(v),
       let d = try? JSONSerialization.data(withJSONObject: v, options: [.sortedKeys]),
       let s = String(data: d, encoding: .utf8) {
        return s
    }
    return "\(v)"
}

@Test func widgetEventCorpusThroughTheHeadlessModule() {
    let cases = corpusCases()
    #expect(cases.count >= 15, "the corpus must not be empty: \(cases.count) cases")
    guard let ws = WorkspaceData.load() else {
        Issue.record("the compiled workspace did not load")
        return
    }
    var failures: [String] = []
    var outcomes: [String: Int] = [:]
    for c in cases {
        let name = c["name"] as? String ?? "(unnamed)"
        guard let panelId = c["panel"] as? String,
              let widgetId = c["widget"] as? String,
              let before = c["before"] as? [String: Any],
              let event = c["event"] as? [String: Any],
              let expected = c["expected"] as? [String: Any],
              let want = expected["result"] as? [String: Any],
              let panelSpec = ws.panel(panelId) else {
            failures.append("\(name): the case or its panel did not read")
            continue
        }
        guard let widget = WidgetEvent.findWidget(in: panelSpec["content"], id: widgetId) else {
            failures.append("\(name): no widget '\(widgetId)' in \(panelId)")
            continue
        }

        let store = StateStore()
        for (k, v) in ws.stateDefaults() { store.set(k, v) }
        for (k, v) in before["state"] as? [String: Any] ?? [:] { store.set(k, v) }
        store.initPanel(panelId, defaults: before["panel"] as? [String: Any] ?? [:])
        store.setActivePanel(panelId)
        let stateBefore = store.getAll()

        let got: WidgetEvent.Result
        if event["press"] != nil {
            got = WidgetEvent.press(widget: widget, store: store, panel: panelSpec,
                                    actions: ws.actions())
        } else {
            got = WidgetEvent.commit(widget: widget, text: event["commit"] as? String,
                                     store: store, panel: panelSpec,
                                     actions: ws.actions())
        }
        outcomes[got.outcome, default: 0] += 1

        let wantOutcome = want["outcome"] as? String
        let wantReason = want["reason"] as? String
        if got.outcome != wantOutcome || got.reason != wantReason {
            failures.append("\(name): \(got.outcome)/\(got.reason ?? "nil"), "
                + "expected \(wantOutcome ?? "?")/\(wantReason ?? "nil")")
        }
        if !sameJson(got.value, want["value"]) {
            failures.append("\(name): value \(show(got.value)), expected \(show(want["value"]))")
        }
        if got.bindWritten != (want["bind_written"] as? Bool) {
            failures.append("\(name): bind_written \(got.bindWritten)")
        }
        if got.behaviorsRun != (want["behaviors_run"] as? Int) {
            failures.append("\(name): behaviors_run \(got.behaviorsRun), "
                + "expected \(show(want["behaviors_run"]))")
        }

        let panelAfter = store.getPanelState(panelId)
        if !sameJson(panelAfter, expected["panel"]) {
            failures.append("\(name): panel \(show(panelAfter)) != \(show(expected["panel"]))")
        }
        var changed: [String: Any] = [:]
        for (k, v) in store.getAll() where !sameJson(stateBefore[k], v) {
            changed[k] = v
        }
        for k in stateBefore.keys where store.getAll()[k] == nil {
            changed[k] = NSNull()
        }
        if !sameJson(changed, expected["state_changed"]) {
            failures.append("\(name): globals changed \(show(changed)) "
                + "!= \(show(expected["state_changed"]))")
        }
    }
    // Every outcome the corpus carries is exercised, so a module that
    // refused everything cannot pass by agreeing with the refusals.
    #expect((outcomes["refused"] ?? 0) > 0 && (outcomes["committed"] ?? 0) > 0,
            "outcomes: \(outcomes)")
    #expect(outcomes.values.reduce(0, +) == cases.count, "outcomes: \(outcomes)")
    let report = failures.joined(separator: "\n")
    #expect(failures.isEmpty, "\(failures.count) of \(cases.count) cases:\n\(report)")
}

/// The lookup the corpus arm rests on, with a control: a nested id is found,
/// and an id that is only a VALUE (not a node's `id`) is not.
@Test func widgetEventFindsANestedWidgetById() {
    let content: [String: Any] = [
        "type": "container",
        "children": [
            ["type": "text", "content": "mwp_fill_tolerance"],
            ["type": "container", "children": [
                ["id": "mwp_fill_tolerance", "type": "number_input"],
            ]],
        ],
    ]
    let found = WidgetEvent.findWidget(in: content, id: "mwp_fill_tolerance")
    #expect(found?["type"] as? String == "number_input")
    #expect(WidgetEvent.findWidget(in: content, id: "absent") == nil)
}

// ── The reference's synthetic arms, for what no shipped widget exercises ──
//
// ⛔ WHY THESE EXIST. The corpus is generated over SHIPPED widgets, and a
// mutation pass over this module (16 mutants) left six alive, every one a
// behaviour no shipped value widget has: a behavior `condition` (measured:
// the only conditions on these kinds are `text_input` `keydown`s, which are
// not commits), a whole-float select option, a `state.` or expression bind,
// and a widget that binds and declares nothing. The reference pins each with
// a synthetic widget (`workspace_interpreter/tests/test_widget_event.py`),
// and these are those tests, ported, with the reference test named on each.

private let probePanel = "probe_panel_content"

private func probeStore(_ panel: [String: Any]) -> StateStore {
    let store = StateStore()
    store.initPanel(probePanel, defaults: panel)
    store.setActivePanel(probePanel)
    return store
}

private func isTrue(_ v: Any?) -> Bool { Value.fromJson(v) == .bool(true) }

/// test_a_false_condition_skips_that_behavior_only
@Test func widgetEventAFalseConditionSkipsThatBehaviorOnly() {
    let store = probeStore(["n": 1])
    let w: [String: Any] = [
        "type": "number_input", "bind": ["value": "panel.n"],
        "behavior": [
            ["event": "commit", "condition": "panel.n > 10",
             "effects": [["set": ["big": "true"]]]],
            ["event": "commit", "effects": [["set": ["any": "true"]]]],
        ],
    ]
    #expect(WidgetEvent.commit(widget: w, text: "5", store: store, panel: nil).behaviorsRun == 1)
    #expect(store.get("big") == nil && isTrue(store.get("any")))
    #expect(WidgetEvent.commit(widget: w, text: "50", store: store, panel: nil).behaviorsRun == 2)
    #expect(isTrue(store.get("big")))
}

/// test_a_declared_behavior_owns_the_press_even_when_its_condition_is_false
@Test func widgetEventADeclaredBehaviorOwnsThePressEvenWhenItsConditionIsFalse() {
    let store = probeStore(["on": true, "armed": false])
    let w: [String: Any] = [
        "type": "toggle", "bind": ["checked": "panel.on"],
        "behavior": [["event": "click", "condition": "panel.armed",
                      "effects": [["set": ["ran": "true"]]]]],
    ]
    let r = WidgetEvent.press(widget: w, store: store, panel: nil)
    #expect(r.outcome == "inert" && r.behaviorsRun == 0 && !r.bindWritten)
    #expect(Value.fromJson(r.value) == .bool(false))
    #expect(isTrue(store.getPanel(probePanel, "on")))
    #expect(store.get("ran") == nil)
}

/// test_writable_is_panel_or_dialog_identifier_only
@Test func widgetEventWritableIsPanelOrDialogIdentifierOnly() {
    #expect(WidgetEvent.writableTarget("panel.fill_tolerance").map { "\($0.scope).\($0.key)" }
            == "panel.fill_tolerance")
    #expect(WidgetEvent.writableTarget(" dialog.web_only ").map { "\($0.scope).\($0.key)" }
            == "dialog.web_only")
    for expr in ["state.magic_wand_fill_color", "selection_mask_clip", "ab.name",
                 "not panel.x", "panel.stops[panel.i].opacity", "panel.", "${bind}"] {
        #expect(WidgetEvent.writableTarget(expr) == nil, "\(expr)")
    }
    #expect(WidgetEvent.writableTarget(nil) == nil)
}

/// test_an_expression_bind_is_read_but_not_written
@Test func widgetEventAnExpressionBindIsReadButNotWritten() {
    let store = probeStore(["mode": "a"])
    let w: [String: Any] = ["type": "toggle", "bind": ["checked": "panel.mode == 'a'"]]
    let r = WidgetEvent.press(widget: w, store: store, panel: nil)
    #expect(r.outcome == "inert" && !r.bindWritten)
    #expect(Value.fromJson(r.value) == .bool(false))
    #expect(store.getPanel(probePanel, "mode") as? String == "a")
}

/// test_nothing_bound_and_nothing_declared_is_inert
@Test func widgetEventNothingBoundAndNothingDeclaredIsInert() {
    let store = probeStore(["n": 1])
    let r = WidgetEvent.commit(widget: ["type": "number_input"], text: "5", store: store,
                               panel: nil)
    #expect(r.outcome == "inert" && r.reason == nil && !r.bindWritten && r.behaviorsRun == 0)
    #expect(Value.fromJson(r.value) == .number(5))
    // The control: the same text into a bound box commits.
    let bound = WidgetEvent.commit(widget: ["type": "number_input", "bind": ["value": "panel.n"]],
                                   text: "5", store: store, panel: nil)
    #expect(bound.outcome == "committed" && bound.bindWritten)
}

/// test_select_takes_the_matching_options_declared_value, with the
/// reference's `str()` of a whole FLOAT added: `str(3.0)` is `3.0`, not `3`.
@Test func widgetEventSelectTakesTheMatchingOptionsDeclaredValue() {
    let w: [String: Any] = ["type": "select", "options": [
        ["label": "Letter", "value": "letter"],
        ["label": "Two", "value": 2],
        ["label": "Three", "value": 3.0],
    ]]
    #expect(WidgetEvent.parseCommit(widget: w, text: "letter").value as? String == "letter")
    #expect(Value.fromJson(WidgetEvent.parseCommit(widget: w, text: "2").value) == .number(2))
    #expect(WidgetEvent.parseCommit(widget: w, text: "3.0").accepted)
    #expect(!WidgetEvent.parseCommit(widget: w, text: "3").accepted)
    #expect(!WidgetEvent.parseCommit(widget: w, text: "Letter").accepted)
    #expect(!WidgetEvent.parseCommit(widget: w, text: "legal").accepted)
}
