import Foundation
import Testing
@testable import JasLib

// The widget event corpus through Swift's headless `WidgetEvent`.
//
// `test_fixtures/widget_events/corpus.json` is GENERATED by the reference
// (`workspace_interpreter/widget_event.py`, `WIDGET_EVENTS.md`). The store
// is seeded as the corpus says a consumer rebuilds it: the bundle's `state`
// defaults, then `before.state`; the widget's panel scope is `before.panel`,
// whole, and that panel is the active panel.
//
// ⛔ STRONGER THAN THE ENGINE'S ARM, ON PURPOSE. The engine's door reports
// no `behaviors_run` or `bind_written`, so `ffi.rs` compares the refusal
// class, the panel scope and the changed globals. This module returns the
// whole result, so ALL of `expected.result` is compared too: outcome,
// reason, value, bind_written and behaviors_run.

private func corpusCases() -> [[String: Any]] {
    let testsDir = ((#filePath as NSString).deletingLastPathComponent as NSString)
        .deletingLastPathComponent
    let path = ((testsDir as NSString)
        .appendingPathComponent("../../test_fixtures/widget_events/corpus.json") as NSString)
        .standardizingPath
    guard let data = FileManager.default.contents(atPath: path),
          let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let cases = root["cases"] as? [[String: Any]] else {
        Issue.record("the widget event corpus did not load from \(path)")
        return []
    }
    return cases
}

/// Numbers as numbers, a JSON boolean as a boolean (never as 0 or 1), a
/// JSON null and a missing value as the same null, recursively.
private func sameJson(_ a: Any?, _ b: Any?) -> Bool {
    let a = a is NSNull ? nil : a
    let b = b is NSNull ? nil : b
    switch (a, b) {
    case (nil, nil):
        return true
    case let (x as [String: Any], y as [String: Any]):
        return x.count == y.count
            && x.allSatisfy { k, v in y.keys.contains(k) && sameJson(v, y[k]) }
    case let (x as [Any], y as [Any]):
        return x.count == y.count && zip(x, y).allSatisfy { sameJson($0, $1) }
    case let (x?, y?):
        return Value.fromJson(x) == Value.fromJson(y)
    default:
        return false
    }
}

private func show(_ v: Any?) -> String {
    guard let v = v, !(v is NSNull) else { return "null" }
    if JSONSerialization.isValidJSONObject(v),
       let d = try? JSONSerialization.data(withJSONObject: v, options: [.sortedKeys]),
       let s = String(data: d, encoding: .utf8) {
        return s
    }
    return "\(v)"
}

@Test func widgetEventCorpusThroughTheHeadlessModule() {
    let cases = corpusCases()
    #expect(cases.count >= 15, "the corpus must not be empty: \(cases.count) cases")
    guard let ws = WorkspaceData.load() else {
        Issue.record("the compiled workspace did not load")
        return
    }
    var failures: [String] = []
    var outcomes: [String: Int] = [:]
    for c in cases {
        let name = c["name"] as? String ?? "(unnamed)"
        guard let panelId = c["panel"] as? String,
              let widgetId = c["widget"] as? String,
              let before = c["before"] as? [String: Any],
              let event = c["event"] as? [String: Any],
              let expected = c["expected"] as? [String: Any],
              let want = expected["result"] as? [String: Any],
              let panelSpec = ws.panel(panelId) else {
            failures.append("\(name): the case or its panel did not read")
            continue
        }
        guard let widget = WidgetEvent.findWidget(in: panelSpec["content"], id: widgetId) else {
            failures.append("\(name): no widget '\(widgetId)' in \(panelId)")
            continue
        }

        let store = StateStore()
        for (k, v) in ws.stateDefaults() { store.set(k, v) }
        for (k, v) in before["state"] as? [String: Any] ?? [:] { store.set(k, v) }
        store.initPanel(panelId, defaults: before["panel"] as? [String: Any] ?? [:])
        store.setActivePanel(panelId)
        let stateBefore = store.getAll()

        let got: WidgetEvent.Result
        if event["press"] != nil {
            got = WidgetEvent.press(widget: widget, store: store, panel: panelSpec,
                                    actions: ws.actions())
        } else {
            got = WidgetEvent.commit(widget: widget, text: event["commit"] as? String,
                                     store: store, panel: panelSpec,
                                     actions: ws.actions())
        }
        outcomes[got.outcome, default: 0] += 1

        let wantOutcome = want["outcome"] as? String
        let wantReason = want["reason"] as? String
        if got.outcome != wantOutcome || got.reason != wantReason {
            failures.append("\(name): \(got.outcome)/\(got.reason ?? "nil"), "
                + "expected \(wantOutcome ?? "?")/\(wantReason ?? "nil")")
        }
        if !sameJson(got.value, want["value"]) {
            failures.append("\(name): value \(show(got.value)), expected \(show(want["value"]))")
        }
        if got.bindWritten != (want["bind_written"] as? Bool) {
            failures.append("\(name): bind_written \(got.bindWritten)")
        }
        if got.behaviorsRun != (want["behaviors_run"] as? Int) {
            failures.append("\(name): behaviors_run \(got.behaviorsRun), "
                + "expected \(show(want["behaviors_run"]))")
        }

        let panelAfter = store.getPanelState(panelId)
        if !sameJson(panelAfter, expected["panel"]) {
            failures.append("\(name): panel \(show(panelAfter)) != \(show(expected["panel"]))")
        }
        var changed: [String: Any] = [:]
        for (k, v) in store.getAll() where !sameJson(stateBefore[k], v) {
            changed[k] = v
        }
        for k in stateBefore.keys where store.getAll()[k] == nil {
            changed[k] = NSNull()
        }
        if !sameJson(changed, expected["state_changed"]) {
            failures.append("\(name): globals changed \(show(changed)) "
                + "!= \(show(expected["state_changed"]))")
        }
    }
    // Every outcome the corpus carries is exercised, so a module that
    // refused everything cannot pass by agreeing with the refusals.
    #expect((outcomes["refused"] ?? 0) > 0 && (outcomes["committed"] ?? 0) > 0,
            "outcomes: \(outcomes)")
    #expect(outcomes.values.reduce(0, +) == cases.count, "outcomes: \(outcomes)")
    let report = failures.joined(separator: "\n")
    #expect(failures.isEmpty, "\(failures.count) of \(cases.count) cases:\n\(report)")
}

/// The lookup the corpus arm rests on, with a control: a nested id is found,
/// and an id that is only a VALUE (not a node's `id`) is not.
@Test func widgetEventFindsANestedWidgetById() {
    let content: [String: Any] = [
        "type": "container",
        "children": [
            ["type": "text", "content": "mwp_fill_tolerance"],
            ["type": "container", "children": [
                ["id": "mwp_fill_tolerance", "type": "number_input"],
            ]],
        ],
    ]
    let found = WidgetEvent.findWidget(in: content, id: "mwp_fill_tolerance")
    #expect(found?["type"] as? String == "number_input")
    #expect(WidgetEvent.findWidget(in: content, id: "absent") == nil)
}
