"""The widget event corpus (test_fixtures/widget_events/corpus.json).

The corpus is GENERATED by running the reference (widget_event.py) over the
compiled bundle, and the active ports and the engine's value door are held
to it. This file is its reference consumer, and it checks three things:

1. **The committed golden is exactly what the reference produces now.** A
   stale golden reds here, not as a confusing port mismatch later.
2. **The golden carries the W2b-1 arms, with the values those arms exist to
   pin.** The expected values are READ from the regenerated file, never
   typed in by hand, except the handful of facts that ARE the arm (for
   example, the order arm's other scale reads the NEW value).
3. **The corpus exercises every outcome and every refusal**, so a generator
   that quietly dropped a class of case cannot stay green.
"""

import importlib.util
import json
import pathlib

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
GOLDEN = ROOT / "test_fixtures" / "widget_events" / "corpus.json"
GENERATOR = ROOT / "scripts" / "gen_widget_event_corpus.py"


def _generator():
    spec = importlib.util.spec_from_file_location("gen_widget_event_corpus", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def golden():
    with GOLDEN.open(encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def cases(golden):
    by_name = {c["name"]: c for c in golden["cases"]}
    assert len(by_name) == len(golden["cases"]), "case names must be unique"
    return by_name


def test_the_golden_is_what_the_reference_produces_now(golden):
    gen = _generator()
    assert gen.render(gen.build()) == GOLDEN.read_text(encoding="utf-8"), (
        "stale golden: run `python scripts/gen_widget_event_corpus.py`")
    assert golden == json.loads(gen.render(gen.build()))


def test_every_case_names_a_real_widget_of_a_contract_kind(golden):
    from workspace_interpreter import widget_event as we
    from workspace_interpreter.loader import find_element_by_id
    bundle = json.loads((ROOT / "workspace" / "workspace.json").read_text(encoding="utf-8"))
    assert len(golden["cases"]) >= 15
    for c in golden["cases"]:
        widget = find_element_by_id(bundle["panels"][c["panel"]], c["widget"])
        assert widget is not None, c["name"]
        assert widget["type"] in we.ALLOWED_EVENTS, c["name"]
        # A press on a boolean kind; a commit on an input kind.
        assert ("press" in c["event"]) == (widget["type"] in we.BOOLEAN_KINDS), c["name"]


def test_every_outcome_and_refusal_is_exercised(golden):
    from workspace_interpreter import widget_event as we
    results = [c["expected"]["result"] for c in golden["cases"]]
    assert {r["outcome"] for r in results} >= {"committed", "refused"}
    assert {r["reason"] for r in results if r["outcome"] == "refused"} == {
        we.BAD_VALUE, we.MISSING_VALUE, we.DISABLED}
    # Both halves of the boolean rule: a press that ran behaviors instead of
    # writing, and one of each input shape that wrote and then ran.
    assert any(r["behaviors_run"] and not r["bind_written"] for r in results)
    assert any(r["behaviors_run"] and r["bind_written"] for r in results)
    assert any(r["bind_written"] and not r["behaviors_run"] for r in results)


def test_a_refused_case_moves_nothing(golden):
    for c in golden["cases"]:
        if c["expected"]["result"]["outcome"] == "refused":
            assert c["expected"]["panel"] == c["before"]["panel"], c["name"]
            assert c["expected"]["state_changed"] == {}, c["name"]


# The W2b-1 arms (block §3). Each asserts the fact the arm exists for.

def test_arm_a_a_commit_reaches_panel_and_tool(cases):
    c = cases["magic_wand_tolerance_commit"]
    assert c["event"] == {"commit": "40"}
    assert c["expected"]["panel"]["fill_tolerance"] == 40
    assert c["expected"]["state_changed"] == {"magic_wand_fill_tolerance": 40}


def test_arm_b_a_commit_without_a_value(cases):
    c = cases["magic_wand_tolerance_missing_value"]
    assert c["event"] == {"commit": None}
    assert c["expected"]["result"]["reason"] == "MissingValue"


def test_arm_c_a_bad_value(cases):
    c = cases["magic_wand_tolerance_bad_value"]
    assert c["event"] == {"commit": "abc"}
    assert c["expected"]["result"]["reason"] == "BadValue"


def test_arm_d_the_order_arm(cases):
    linked = cases["stroke_start_scale_linked"]
    assert linked["before"]["panel"]["link_arrowhead_scale"] is True
    assert linked["before"]["panel"]["end_arrowhead_scale"] != 200
    assert linked["expected"]["panel"]["end_arrowhead_scale"] == 200
    assert linked["expected"]["state_changed"]["stroke_end_arrowhead_scale"] == 200
    unlinked = cases["stroke_start_scale_unlinked"]
    assert unlinked["expected"]["panel"]["end_arrowhead_scale"] == \
        unlinked["before"]["panel"]["end_arrowhead_scale"]


def test_the_two_way_bind_reaches_the_global_init_reads(cases):
    weight = cases["stroke_weight_in_inches"]
    assert weight["expected"]["panel"]["weight"] == 216
    assert weight["expected"]["state_changed"] == {"stroke_width": 216}
    unlinked = cases["stroke_start_scale_unlinked"]
    assert unlinked["expected"]["state_changed"] == {"stroke_start_arrowhead_scale": 200}
    cleared = cases["stroke_dash_2_cleared"]
    assert cleared["expected"]["state_changed"] == {"stroke_dash_2": None}


def test_arm_e_a_toggle_press_flips_panel_and_tool_once(cases):
    for name, key in (("magic_wand_fill_color_press", "fill_color"),
                      ("magic_wand_blending_mode_press", "blending_mode")):
        c = cases[name]
        before = c["before"]["panel"][key]
        assert c["expected"]["panel"][key] is (not before), name
        assert c["expected"]["state_changed"] == {f"magic_wand_{key}": not before}, name
        assert c["expected"]["result"]["bind_written"] is False, name
