//! Workspace loader — parses compiled JSON and extracts panel specs,
//! actions, state defaults, and theme.

use serde_json;
use std::collections::HashMap;
use std::sync::OnceLock;

/// Compiled workspace JSON, embedded at build time.
///
/// This file is generated by:
///   python -m workspace_interpreter.compile workspace/ workspace/workspace.json
const WORKSPACE_JSON: &str = include_str!("../../../workspace/workspace.json");

/// Cached parsed workspace data (parsed once, reused forever).
static WORKSPACE_CACHE: OnceLock<serde_json::Value> = OnceLock::new();

/// Parsed workspace data.
pub struct Workspace {
    data: &'static serde_json::Value,
}

impl Workspace {
    /// Load the workspace from the cached parsed JSON.
    pub fn load() -> Option<Self> {
        let data = WORKSPACE_CACHE.get_or_init(|| {
            serde_json::from_str(WORKSPACE_JSON).unwrap_or(serde_json::Value::Null)
        });
        if data.is_null() { return None; }
        Some(Workspace { data })
    }

    /// Get the full workspace data.
    pub fn data(&self) -> &serde_json::Value {
        &self.data
    }

    /// Get the panels map.
    pub fn panels(&self) -> &serde_json::Value {
        self.data.get("panels").unwrap_or(&serde_json::Value::Null)
    }

    /// Get a specific panel spec by content id.
    pub fn panel(&self, content_id: &str) -> Option<&serde_json::Value> {
        self.data.get("panels")?.get(content_id)
    }

    /// Get the icons map.
    pub fn icons(&self) -> &serde_json::Value {
        self.data.get("icons").unwrap_or(&serde_json::Value::Null)
    }

    /// Get the actions map.
    pub fn actions(&self) -> &serde_json::Value {
        self.data.get("actions").unwrap_or(&serde_json::Value::Null)
    }

    /// Get the state definitions.
    pub fn state_defs(&self) -> &serde_json::Value {
        self.data.get("state").unwrap_or(&serde_json::Value::Null)
    }

    /// Extract default values from state definitions.
    pub fn state_defaults(&self) -> HashMap<String, serde_json::Value> {
        let mut defaults = HashMap::new();
        if let serde_json::Value::Object(map) = self.state_defs() {
            for (key, defn) in map {
                let default_val = if let serde_json::Value::Object(d) = defn {
                    d.get("default").cloned().unwrap_or(serde_json::Value::Null)
                } else {
                    defn.clone()
                };
                defaults.insert(key.clone(), default_val);
            }
        }
        defaults
    }

    /// Extract default values from a panel's state section.
    pub fn panel_state_defaults(&self, content_id: &str) -> HashMap<String, serde_json::Value> {
        let mut defaults = HashMap::new();
        if let Some(panel) = self.panel(content_id) {
            if let Some(serde_json::Value::Object(state)) = panel.get("state") {
                for (key, defn) in state {
                    let default_val = if let serde_json::Value::Object(d) = defn {
                        d.get("default").cloned().unwrap_or(serde_json::Value::Null)
                    } else {
                        defn.clone()
                    };
                    defaults.insert(key.clone(), default_val);
                }
            }
        }
        defaults
    }

    /// Get the panel menu items for a content id.
    pub fn panel_menu(&self, content_id: &str) -> Vec<serde_json::Value> {
        self.panel(content_id)
            .and_then(|p| p.get("menu"))
            .and_then(|m| m.as_array())
            .cloned()
            .unwrap_or_default()
    }

    /// Get the panel content element tree for a content id.
    pub fn panel_content(&self, content_id: &str) -> Option<&serde_json::Value> {
        self.panel(content_id)?.get("content")
    }

    /// Get the theme data.
    pub fn theme(&self) -> &serde_json::Value {
        self.data.get("theme").unwrap_or(&serde_json::Value::Null)
    }

    /// Get the dialogs map.
    pub fn dialogs(&self) -> &serde_json::Value {
        self.data.get("dialogs").unwrap_or(&serde_json::Value::Null)
    }

    /// Get a specific dialog spec by id.
    pub fn dialog(&self, id: &str) -> Option<&serde_json::Value> {
        self.data.get("dialogs")?.get(id)
    }

    /// Extract default values from a dialog's state section.
    pub fn dialog_state_defaults(&self, id: &str) -> HashMap<String, serde_json::Value> {
        let mut defaults = HashMap::new();
        if let Some(dialog) = self.dialog(id) {
            if let Some(serde_json::Value::Object(state)) = dialog.get("state") {
                for (key, defn) in state {
                    let default_val = if let serde_json::Value::Object(d) = defn {
                        d.get("default").cloned().unwrap_or(serde_json::Value::Null)
                    } else {
                        defn.clone()
                    };
                    defaults.insert(key.clone(), default_val);
                }
            }
        }
        defaults
    }
}

/// Map PanelKind to YAML content id.
#[cfg(feature = "web")]
pub fn panel_kind_to_content_id(kind: crate::workspace::workspace::PanelKind) -> &'static str {
    use crate::workspace::workspace::PanelKind;
    match kind {
        PanelKind::Layers => "layers_panel_content",
        PanelKind::Color => "color_panel_content",
        PanelKind::Swatches => "swatches_panel_content",
        PanelKind::Stroke => "stroke_panel_content",
        PanelKind::Properties => "properties_panel_content",
        PanelKind::Character => "character_panel_content",
        PanelKind::Paragraph => "paragraph_panel_content",
        PanelKind::Artboards => "artboards_panel_content",
        PanelKind::Align => "align_panel_content",
        PanelKind::Boolean => "boolean_panel_content",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_workspace() {
        let ws = Workspace::load().expect("Failed to load workspace");
        assert!(ws.panels().is_object());
        assert!(ws.actions().is_object());
    }

    #[test]
    fn panel_specs_present() {
        let ws = Workspace::load().unwrap();
        assert!(ws.panel("color_panel_content").is_some());
        assert!(ws.panel("layers_panel_content").is_some());
    }

    #[test]
    fn color_panel_has_menu() {
        let ws = Workspace::load().unwrap();
        let menu = ws.panel_menu("color_panel_content");
        assert!(!menu.is_empty());
    }

    #[test]
    fn color_panel_has_content() {
        let ws = Workspace::load().unwrap();
        assert!(ws.panel_content("color_panel_content").is_some());
    }

    #[test]
    fn state_defaults_extracted() {
        let ws = Workspace::load().unwrap();
        let defaults = ws.state_defaults();
        assert!(defaults.contains_key("active_tool"));
        assert!(defaults.contains_key("fill_color"));
    }

    #[test]
    fn panel_state_defaults_extracted() {
        let ws = Workspace::load().unwrap();
        let defaults = ws.panel_state_defaults("color_panel_content");
        assert!(defaults.contains_key("mode"));
        assert!(defaults.contains_key("h"));
    }

    #[test]
    fn dialogs_present() {
        let ws = Workspace::load().unwrap();
        assert!(ws.dialogs().is_object());
        assert!(ws.dialogs().as_object().unwrap().len() > 0);
    }

    #[test]
    fn color_picker_dialog_exists() {
        let ws = Workspace::load().unwrap();
        let dialog = ws.dialog("color_picker");
        assert!(dialog.is_some());
        let dialog = dialog.unwrap();
        assert_eq!(dialog.get("summary").and_then(|v| v.as_str()), Some("Select Color"));
        assert!(dialog.get("state").is_some());
        assert!(dialog.get("init").is_some());
        assert!(dialog.get("content").is_some());
    }

    #[test]
    fn dialog_state_defaults_extracted() {
        let ws = Workspace::load().unwrap();
        let defaults = ws.dialog_state_defaults("color_picker");
        // color is a plain stored variable with a default
        assert!(defaults.contains_key("color"));
        assert_eq!(defaults.get("color"), Some(&serde_json::json!("#ffffff")));
        // h has a get expression, so no default in defaults
        // (it's computed from color)
    }

    #[test]
    fn workspace_save_as_dialog() {
        let ws = Workspace::load().unwrap();
        let dialog = ws.dialog("workspace_save_as");
        assert!(dialog.is_some());
        let defaults = ws.dialog_state_defaults("workspace_save_as");
        assert!(defaults.contains_key("name"));
    }

    #[test]
    fn color_panel_slider_visibility() {
        use super::super::expr;
        let ws = Workspace::load().unwrap();
        let content = ws.panel_content("color_panel_content").unwrap();
        let state_map: serde_json::Map<String, serde_json::Value> =
            ws.state_defaults().into_iter().collect();
        let panel_map: serde_json::Map<String, serde_json::Value> =
            ws.panel_state_defaults("color_panel_content").into_iter().collect();
        let ctx = serde_json::json!({"state": state_map, "panel": panel_map});

        // Find slider containers by walking children
        fn find_bind_visible(el: &serde_json::Value, results: &mut Vec<(String, String)>) {
            if let Some(id) = el.get("id").and_then(|v| v.as_str()) {
                if let Some(vis) = el.get("bind")
                    .and_then(|b| b.get("visible"))
                    .and_then(|v| v.as_str())
                {
                    results.push((id.to_string(), vis.to_string()));
                }
            }
            if let Some(children) = el.get("children").and_then(|c| c.as_array()) {
                for child in children {
                    find_bind_visible(child, results);
                }
            }
        }

        let mut bindings = Vec::new();
        find_bind_visible(content, &mut bindings);

        // Default mode is "hsb" — only HSB should be visible
        let mut hsb_visible = false;
        let mut others_hidden = true;
        for (id, vis_expr) in &bindings {
            let result = expr::eval(vis_expr, &ctx);
            let visible = result.to_bool();
            // {id}: expr={vis_expr} -> {result:?} visible={visible}
            if id.contains("hsb") {
                hsb_visible = visible;
            } else {
                if visible {
                    others_hidden = false;
                }
            }
        }
        assert!(!bindings.is_empty(), "should find bind:visible expressions");
        assert!(hsb_visible, "HSB sliders should be visible");
        assert!(others_hidden, "non-HSB sliders should be hidden");
    }
}
