//! Workspace loader — parses compiled JSON and extracts panel specs,
//! actions, state defaults, and theme.

use serde_json;
use std::collections::HashMap;

/// Compiled workspace JSON, embedded at build time.
///
/// This file is generated by:
///   python -m workspace_interpreter.compile workspace/ workspace/workspace.json
const WORKSPACE_JSON: &str = include_str!("../../../workspace/workspace.json");

/// Parsed workspace data.
pub struct Workspace {
    data: serde_json::Value,
}

impl Workspace {
    /// Load the workspace from the embedded JSON.
    pub fn load() -> Option<Self> {
        let data: serde_json::Value = serde_json::from_str(WORKSPACE_JSON).ok()?;
        Some(Workspace { data })
    }

    /// Get the full workspace data.
    pub fn data(&self) -> &serde_json::Value {
        &self.data
    }

    /// Get the panels map.
    pub fn panels(&self) -> &serde_json::Value {
        self.data.get("panels").unwrap_or(&serde_json::Value::Null)
    }

    /// Get a specific panel spec by content id.
    pub fn panel(&self, content_id: &str) -> Option<&serde_json::Value> {
        self.data.get("panels")?.get(content_id)
    }

    /// Get the actions map.
    pub fn actions(&self) -> &serde_json::Value {
        self.data.get("actions").unwrap_or(&serde_json::Value::Null)
    }

    /// Get the state definitions.
    pub fn state_defs(&self) -> &serde_json::Value {
        self.data.get("state").unwrap_or(&serde_json::Value::Null)
    }

    /// Extract default values from state definitions.
    pub fn state_defaults(&self) -> HashMap<String, serde_json::Value> {
        let mut defaults = HashMap::new();
        if let serde_json::Value::Object(map) = self.state_defs() {
            for (key, defn) in map {
                let default_val = if let serde_json::Value::Object(d) = defn {
                    d.get("default").cloned().unwrap_or(serde_json::Value::Null)
                } else {
                    defn.clone()
                };
                defaults.insert(key.clone(), default_val);
            }
        }
        defaults
    }

    /// Extract default values from a panel's state section.
    pub fn panel_state_defaults(&self, content_id: &str) -> HashMap<String, serde_json::Value> {
        let mut defaults = HashMap::new();
        if let Some(panel) = self.panel(content_id) {
            if let Some(serde_json::Value::Object(state)) = panel.get("state") {
                for (key, defn) in state {
                    let default_val = if let serde_json::Value::Object(d) = defn {
                        d.get("default").cloned().unwrap_or(serde_json::Value::Null)
                    } else {
                        defn.clone()
                    };
                    defaults.insert(key.clone(), default_val);
                }
            }
        }
        defaults
    }

    /// Get the panel menu items for a content id.
    pub fn panel_menu(&self, content_id: &str) -> Vec<serde_json::Value> {
        self.panel(content_id)
            .and_then(|p| p.get("menu"))
            .and_then(|m| m.as_array())
            .cloned()
            .unwrap_or_default()
    }

    /// Get the panel content element tree for a content id.
    pub fn panel_content(&self, content_id: &str) -> Option<&serde_json::Value> {
        self.panel(content_id)?.get("content")
    }

    /// Get the theme data.
    pub fn theme(&self) -> &serde_json::Value {
        self.data.get("theme").unwrap_or(&serde_json::Value::Null)
    }
}

/// Map PanelKind to YAML content id.
pub fn panel_kind_to_content_id(kind: crate::workspace::workspace::PanelKind) -> &'static str {
    use crate::workspace::workspace::PanelKind;
    match kind {
        PanelKind::Layers => "layers_panel_content",
        PanelKind::Color => "color_panel_content",
        PanelKind::Stroke => "stroke_panel_content",
        PanelKind::Properties => "properties_panel_content",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_workspace() {
        let ws = Workspace::load().expect("Failed to load workspace");
        assert!(ws.panels().is_object());
        assert!(ws.actions().is_object());
    }

    #[test]
    fn panel_specs_present() {
        let ws = Workspace::load().unwrap();
        assert!(ws.panel("color_panel_content").is_some());
        assert!(ws.panel("layers_panel_content").is_some());
    }

    #[test]
    fn color_panel_has_menu() {
        let ws = Workspace::load().unwrap();
        let menu = ws.panel_menu("color_panel_content");
        assert!(!menu.is_empty());
    }

    #[test]
    fn color_panel_has_content() {
        let ws = Workspace::load().unwrap();
        assert!(ws.panel_content("color_panel_content").is_some());
    }

    #[test]
    fn state_defaults_extracted() {
        let ws = Workspace::load().unwrap();
        let defaults = ws.state_defaults();
        assert!(defaults.contains_key("active_tool"));
        assert!(defaults.contains_key("fill_color"));
    }

    #[test]
    fn panel_state_defaults_extracted() {
        let ws = Workspace::load().unwrap();
        let defaults = ws.panel_state_defaults("color_panel_content");
        assert!(defaults.contains_key("mode"));
        assert!(defaults.contains_key("h"));
    }
}
