# OCaml Jas Tests
#
# Built using Dune build system integrated with Bazel.

filegroup(
    name = "test_files",
    srcs = [
        "dune",
        "jas_test.ml",
    ],
    visibility = ["//jas_ocaml:__subpackages__"],
)
