#!/bin/bash
# Verify the panel goldens are up-to-date with the shared layout / widget_tree
# passes and the compiled bundle (codebase-review finding #32).
#
# Both test_fixtures/algorithms/panel_layout.json and
# test_fixtures/algorithms/panel_widget_tree.json are generated by
# scripts/gen_panel_layout_fixture.py from the same seed panels/ctx. Neither
# had a freshness gate — panel_widget_tree.json had no generator at all — so a
# stale golden would surface as a confusing "all four apps mismatch" instead of
# "golden out of date, regenerate."
#
# Read-only: it backs up the goldens, regenerates, diffs, and restores.
# Remedy on failure:
#   python scripts/gen_panel_layout_fixture.py
#   git add test_fixtures/algorithms/panel_layout.json test_fixtures/algorithms/panel_widget_tree.json

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

LAYOUT="test_fixtures/algorithms/panel_layout.json"
TREE="test_fixtures/algorithms/panel_widget_tree.json"

TMP="$(mktemp -d)"
trap 'cp "$TMP/layout" "$LAYOUT"; cp "$TMP/tree" "$TREE"; rm -rf "$TMP"' EXIT

cp "$LAYOUT" "$TMP/layout"
cp "$TREE" "$TMP/tree"

python scripts/gen_panel_layout_fixture.py >/dev/null

rc=0
diff -q "$TMP/layout" "$LAYOUT" >/dev/null || rc=1
diff -q "$TMP/tree" "$TREE" >/dev/null || rc=1

if [ "$rc" -ne 0 ]; then
    echo "ERROR: panel goldens are out of date relative to the layout / widget_tree" >&2
    echo "pass or the compiled bundle. Regenerate and commit:" >&2
    echo "  python scripts/gen_panel_layout_fixture.py" >&2
    echo "  git add $LAYOUT $TREE" >&2
    exit 1
fi

echo "panel goldens (layout + widget_tree) are up to date."
