#!/bin/bash
# Verify the panel goldens are up-to-date with the shared layout / widget_tree /
# bind_values passes and the compiled bundle (codebase-review finding #32).
#
# The goldens under test_fixtures/algorithms/ are generated by
# scripts/gen_panel_layout_fixture.py from the same seed panels/ctx. They had no
# freshness gate — panel_widget_tree.json had no generator at all — so a stale
# golden would surface as a confusing "all four apps mismatch" instead of
# "golden out of date, regenerate."
#
# Read-only: it backs up the goldens, regenerates, diffs, and RESTORES.
#
# The backup list is DERIVED, not enumerated. An earlier version named two files
# explicitly while the generator wrote three, so `bind_values` — added later —
# was regenerated in place and never restored. On macOS/Linux that was invisible
# (the rewritten bytes are identical, so `git status` stayed clean); on Windows
# the rewrite lands as CRLF and the file shows up modified. The gate told the
# truth about its result and a lie about its method.
#
# So: back up the whole golden DIRECTORY, and assert the generator wrote nothing
# outside it. A fourth golden is then covered on the day it is added, and if one
# ever lands elsewhere this gate fails loudly instead of silently under-covering.
#
# Remedy on failure:
#   python scripts/gen_panel_layout_fixture.py
#   git add test_fixtures/algorithms/

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

GOLDEN_DIR="test_fixtures/algorithms"

TMP="$(mktemp -d)"
BACKUP="$TMP/backup"
# Restore unconditionally, whatever the exit path: the whole directory goes back
# exactly as it was found.
trap 'if [ -d "$BACKUP" ]; then cp -p "$BACKUP"/* "$GOLDEN_DIR"/ 2>/dev/null || true; fi; rm -rf "$TMP"' EXIT

mkdir -p "$BACKUP"
cp -p "$GOLDEN_DIR"/* "$BACKUP"/

python scripts/gen_panel_layout_fixture.py > "$TMP/gen.out"

# The generator announces each artifact as "... -> <path>". Every one of those
# must live inside the directory we backed up, or our restore is incomplete and
# the read-only claim is false again.
# Compare DIRECTORIES, not string prefixes. The generator builds its paths with
# os.path.join, so on Windows it reports "...\test_fixtures\algorithms\x.json"
# while $REPO_ROOT here is a POSIX-style "/c/Users/...". Prefix-matching those
# raw would fail on Windows for every file — the same separator assumption this
# commit fixes in genericity_check.py, reintroduced one layer up. Normalise the
# separators, then compare the parent directory.
escaped_out=0
while IFS= read -r written; do
    [ -z "$written" ] && continue
    norm="${written//\\//}"
    case "$(dirname "$norm")" in
        */"$GOLDEN_DIR"|"$GOLDEN_DIR") ;;
        *)
            echo "ERROR: the generator wrote outside $GOLDEN_DIR:" >&2
            echo "  $written" >&2
            escaped_out=1
            ;;
    esac
done < <(sed -n 's/.*-> //p' "$TMP/gen.out")

if [ "$escaped_out" -ne 0 ]; then
    echo >&2
    echo "This gate backs up and restores $GOLDEN_DIR only, so it can no longer" >&2
    echo "promise to be read-only. Extend the backup to cover the path above." >&2
    exit 1
fi

rc=0
stale=""
for f in "$BACKUP"/*; do
    name="$(basename "$f")"
    if ! diff -q "$f" "$GOLDEN_DIR/$name" >/dev/null; then
        rc=1
        stale="$stale  $GOLDEN_DIR/$name"$'\n'
    fi
done

if [ "$rc" -ne 0 ]; then
    echo "ERROR: panel goldens are out of date relative to the layout /" >&2
    echo "widget_tree / bind_values pass or the compiled bundle:" >&2
    printf '%s' "$stale" >&2
    echo >&2
    echo "Regenerate and commit:" >&2
    echo "  python scripts/gen_panel_layout_fixture.py" >&2
    echo "  git add $GOLDEN_DIR/" >&2
    exit 1
fi

echo "panel goldens ($(ls "$BACKUP" | wc -l | tr -d ' ') files in $GOLDEN_DIR) are up to date."
