#!/usr/bin/env python3
"""The title oracle's suite ran EVERY case it declares -- by name, not by a floor.

WHY THIS EXISTS
---------------
`prototypes/sb_winui_tests` is the title oracle's behavioural suite: pure
functions over strings, and the only part of the WinUI-3 prototype a runner with
no desktop can execute. It exists because on kenai 2026-09-04 the session-1 title
oracle FAILED THREE RUNS THAT SUCCEEDED, and the rule that fixes that is what
these cases pin.

`dotnet run` returns the program's exit code, so a FAILING case reds the step on
its own. The hole is the other direction: **a program that stopped running cases
still exits 0**, and every remaining case still passes. Until 2026-09-06 the
anti-vacuity control for that step was

    if [ "${n:-0}" -lt 20 ]; then ... exit 1

and the suite ran **33** cases. Thirteen of thirty-three -- 39% -- could stop
executing with the step green, INCLUDING both cases named `CONTROL:` and all
three of the kenai regression rows the suite was written for. That was measured
at the object (CI run 34034173431), not argued.

⛔ THE FLOOR WAS NOT MERELY "THE WEAKER FORM". It was recorded in this seat's
bank as *"not a hole -- the weaker form, whose number ages"*, and nobody had read
the count in either direction. Calling a defect stylistic prices it as taste, and
taste does not get a number attached.

WHY NAMED ANCHORS, AND NOT A BIGGER FLOOR OR A DERIVED TOTAL
------------------------------------------------------------
Raising 20 to 33 is the move this repo has already rejected once, in writing. The
wasm-canvas step ended in `-lt 4` until 2026-08-30 and its comment says: *"Raising
4 to 17 would rot the same way and teach the next reader to bump it."*

A derived TOTAL would be better and is still not enough here. The sibling control
in the `windows` job (`harness_selftest.ps1`) counts unconditional `Test-Case`
declarations for a lower bound, and the same idea gives 22 for this file -- but 11
of the 33 cases are generated by a `foreach` over a data set, so a
declaration count alone is blind to a third of the suite.

So this gate takes the pattern `check_rust_suite_ran.py` established in this repo
on 2026-09-06: **a named case is immune.** Every unconditionally-declared case
must appear in the log as executed and passing, BY ITS OWN NAME, so the gate says
WHICH case stopped rather than that some number of them did. Data-driven cases are
covered by deriving the size of the data set they iterate and requiring that many
executions under their name's literal prefix.

⭐ AND EVERY DECLARATION IS DERIVED FROM THE SOURCE ON EVERY RUN. Nothing here is
a list someone must remember to update: add a case and it is required from the
next run on. The number 33 appears nowhere in this file except in the prose above,
describing the day it was written.

⚠️ BE EXACT ABOUT WHAT REDS, because the tempting sentence is false. This gate
reds when a case stops running while its DECLARATION REMAINS. A deliberate
deletion moves both sides at once and passes -- correctly, because the source is
the spec, and a gate that fought its own subject's edits would be bumped into
silence within a week. What it removes is the silent case: the declaration still
sitting there, and nothing executing it.

A DECLARATION SHAPE IT CANNOT BOUND IS A REFUSAL, NEVER AN OMISSION
-------------------------------------------------------------------
The dangerous failure for a gate like this is silent under-derivation: a case
shape the parser does not recognise contributes nothing to the requirement, so
the gate goes green having asked for less. Every path here refuses instead:

  * zero unconditional anchors derived  -> REFUSED (cannot derive its subject)
  * an interpolated case name outside any derivable loop -> REFUSED (a
    declaration shape that cannot be bounded is not a satisfied declaration)
  * a `foreach` whose data set or whose case name cannot be read -> REFUSED
  * a missing or empty log, or one with no summary line -> REFUSED

⚠️ WHAT THIS GATE DOES NOT COVER, stated because a caveat block is the honest
place for it. It bounds executions from BELOW. Cases added inside an `if` push the
executed total above the derived requirement and are not individually required --
growth never reds this gate, by design, exactly as the `.ps1` sibling argues. The
one shape that would defeat it is a case declared at top level whose name is a
`const` rather than a literal; there are none today, and such a site would be an
interpolation-free call this parser does not see. If that shape is ever added,
`--self-test` arm `unbounded-shape` is the arm to extend.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = REPO / "prototypes" / "sb_winui_tests" / "Program.cs"

# A statement in the body of a method of a top-level static class sits at eight
# spaces. That is what "unconditional" means for this file: the call is a
# statement of `Main`, not of a loop, an `if`, or a lambda, all of which indent
# further. The assumption is not left to trust -- deriving ZERO anchors is a
# refusal below, and `--self-test` drives the real source to prove the shape
# still matches the artifact.
TOP_LEVEL_INDENT = 8

# `Check(name, ...)` inside the `Eq` helper's own body also sits at eight spaces.
# Requiring a string LITERAL as the first argument is what separates a case
# declaration from the helper that forwards one. Arm `helper-body` pins it.
EXACT_CASE = re.compile(
    r'^ {%d}(?:Check|Eq)\("((?:[^"\\]|\\.)*)"' % TOP_LEVEL_INDENT
)

# A case whose name is interpolated: the literal prefix runs up to the first `{`.
INTERPOLATED_CASE = re.compile(r'^\s*(?:Check|Eq)\(\$"((?:[^"\\{]|\\.)*)\{')

FOREACH_OPEN = re.compile(r"^ {%d}foreach \(var \w+ in new\[\] \{$" % TOP_LEVEL_INDENT)
FOREACH_DATA_CLOSE = re.compile(r"^ {%d}\}\)$" % TOP_LEVEL_INDENT)
FOREACH_BODY_CLOSE = re.compile(r"^ {%d}\}$" % TOP_LEVEL_INDENT)
DATA_ENTRY = re.compile(r'^\s*"(?:[^"\\]|\\.)*",?$')

EXECUTED = re.compile(r"^  pass  (.*)$")
FAILED = re.compile(r"^  FAIL  (.*?)(?:  --  .*)?$")
SUMMARY = re.compile(
    r"^--- (\d+) passed, (\d+) failed, of (\d+) case\(s\) ---$", re.MULTILINE
)


class Refusal(Exception):
    """The gate cannot establish what it is supposed to require."""


# --------------------------------------------------------------------------
# Deriving the declaration from the source
# --------------------------------------------------------------------------


def _loop_blocks(lines: list[str]) -> list[tuple[str, int, int]]:
    """Every data-driven case family: (name prefix, data-set size, header line).

    A `foreach (var x in new[] { ... })` whose body declares a case with an
    interpolated name is one family. Both halves must be readable or the whole
    block is a refusal: a family whose size cannot be counted, or whose name
    cannot be read, is a set of cases this gate would otherwise silently stop
    requiring.
    """
    blocks: list[tuple[str, int, int]] = []
    i = 0
    while i < len(lines):
        if not FOREACH_OPEN.match(lines[i]):
            i += 1
            continue
        header = i
        i += 1
        size = 0
        while i < len(lines) and not FOREACH_DATA_CLOSE.match(lines[i]):
            if DATA_ENTRY.match(lines[i]):
                size += 1
            elif lines[i].strip() and not lines[i].lstrip().startswith("//"):
                raise Refusal(
                    "line %d: the data set of the loop opened at line %d holds an "
                    "entry this gate cannot count (%r) -- an uncountable family is "
                    "a refusal, not zero cases"
                    % (i + 1, header + 1, lines[i].strip()[:60])
                )
            i += 1
        if i >= len(lines):
            raise Refusal(
                "the loop opened at line %d has no closing `})` -- its data set "
                "cannot be sized" % (header + 1)
            )
        if size < 1:
            raise Refusal(
                "the loop opened at line %d iterates an EMPTY data set, so it "
                "declares no case at all" % (header + 1)
            )
        # The body runs from the `})` to the foreach's own closing brace.
        body_start = i
        i += 1
        prefix: str | None = None
        while i < len(lines) and not FOREACH_BODY_CLOSE.match(lines[i]):
            m = INTERPOLATED_CASE.match(lines[i])
            if m and prefix is None:
                prefix = m.group(1)
            i += 1
        if prefix is None:
            # ⭐ A LOOP THAT DECLARES NO CASE IS NOT A CASE FAMILY, and refusing on
            # one would red this gate on an ordinary setup loop -- a false red,
            # which is its own defect and the fastest route to a gate being
            # weakened to shut it up. But "declares nothing" must be MEASURED, not
            # assumed from a parse that came back empty: a body that calls
            # `Check`/`Eq` in a form this parser cannot read declares an unknown
            # number of cases, and THAT is the shape that must never be ignored.
            body = "\n".join(lines[body_start:i])
            if re.search(r"\b(?:Check|Eq)\(", body):
                raise Refusal(
                    "the loop opened at line %d declares case(s) whose name this "
                    "gate cannot read, so its %d iteration(s) cannot be required "
                    "-- an unreadable declaration is not an absent one"
                    % (header + 1, size)
                )
            i += 1
            continue
        if not prefix.strip():
            raise Refusal(
                "the loop opened at line %d names its cases with an empty literal "
                "prefix, which matches every line and requires nothing"
                % (header + 1)
            )
        blocks.append((prefix, size, body_start))
        i += 1
    return blocks


def declaration(source_text: str) -> tuple[list[str], list[tuple[str, int, int]]]:
    """(exact case names, data-driven families) -- or a Refusal."""
    lines = source_text.splitlines()
    exact = [m.group(1) for m in (EXACT_CASE.match(ln) for ln in lines) if m]
    loops = _loop_blocks(lines)

    if not exact:
        raise Refusal(
            "no unconditional case declaration found in the source -- this gate "
            "cannot derive its subject, which is a refusal and not a pass"
        )

    # ⛔ THE GUARD THAT KEEPS UNDER-DERIVATION FROM READING AS SUCCESS. Any
    # interpolated case name that is NOT inside a family we sized is a set of
    # cases of unknown size. Ignoring it would quietly shrink what this gate
    # asks for, which is the exact failure mode it exists to prevent.
    accounted = set()
    for _prefix, _size, body_start in loops:
        j = body_start
        while j < len(lines) and not FOREACH_BODY_CLOSE.match(lines[j]):
            accounted.add(j)
            j += 1
    for n, ln in enumerate(lines):
        if INTERPOLATED_CASE.match(ln) and n not in accounted:
            raise Refusal(
                "line %d declares a case with an interpolated name outside any "
                "loop this gate can size (%r) -- a declaration shape that cannot "
                "be bounded is not a satisfied declaration"
                % (n + 1, ln.strip()[:70])
            )

    dupes = {n for n in exact if exact.count(n) > 1}
    if dupes:
        raise Refusal(
            "case name(s) declared more than once, so one of each pair could stop "
            "running behind the other: %s" % ", ".join(sorted(dupes)[:3])
        )
    return exact, loops


# --------------------------------------------------------------------------
# Adjudicating the log
# --------------------------------------------------------------------------


def findings(source_text: str, log: str) -> list[str]:
    exact, loops = declaration(source_text)
    required = len(exact) + sum(size for _p, size, _b in loops)

    m = SUMMARY.search(log)
    if not m:
        raise Refusal(
            "no summary line in the suite's output, so nothing proves a case "
            "executed"
        )
    passed, failed, total = (int(g) for g in m.groups())
    if total < 1:
        raise Refusal(
            "the summary reports %d case(s) -- the suite examined nothing, which "
            "is not a pass" % total
        )

    out: list[str] = []
    if passed + failed != total:
        out.append(
            "the summary does not add up: %d passed + %d failed != %d total"
            % (passed, failed, total)
        )
    if failed:
        for line in log.splitlines():
            f = FAILED.match(line)
            if f:
                out.append("case FAILED: %s" % f.group(1).strip())
        if not any(s.startswith("case FAILED") for s in out):
            out.append("the summary reports %d failed case(s)" % failed)

    # ⛔ A LIST, NOT A SET, AND THE REAL ARTIFACT IS WHY. The first cut of this
    # gate collected executed case names into a set and reported 9 executions of
    # an 11-row family against the REAL CI log (run 34034173431). The suite's
    # data-driven names are built from each row's FIRST TOKEN, and three of the
    # eleven rows begin `RESIZE`, so three distinct executions share one name. A
    # set silently under-counts exactly where a family's names collide, which is
    # a spurious red here and would be a hole in the mirror case. Executions are
    # counted; identity by name is asserted only where names are unique.
    executed = [m2.group(1) for m2 in (EXECUTED.match(ln) for ln in log.splitlines()) if m2]
    for name in exact:
        if name not in executed:
            out.append(
                "declared case did not run (or did not pass): %s" % name
            )

    for prefix, size, header in loops:
        seen = sum(1 for name in executed if name.startswith(prefix))
        if seen < size:
            out.append(
                "the data-driven family %r ran %d case(s) but its data set (line "
                "%d) holds %d -- cases stopped running while the rest passed"
                % (prefix, seen, header + 1, size)
            )

    if total < required:
        out.append(
            "the suite reports %d case(s) but the source declares %d "
            "unconditionally (%d named + %d data-driven)"
            % (total, required, len(exact), required - len(exact))
        )
    return out


# --------------------------------------------------------------------------
# Self-test
# --------------------------------------------------------------------------

_GOOD_SOURCE = '''static class Program
{
    static void Check(string name, bool ok, string detail)
    {
        if (ok) { _passed++; }
    }

    static void Eq(string name, string expected, string actual) =>
        Check(name, expected == actual, $"expected '{expected}', got '{actual}'");

    static int Main()
    {
        Eq("alpha holds", "a", "a");
        Check("beta holds", true, "");

        foreach (var row in new[] {
            "ONE first",
            "TWO second",
            "THREE third",
        })
        {
            Eq($"row carries: '{row.Split(' ')[0]}'", "x", "x");
        }

        Check("CONTROL: gamma does not", false == false, "");
        return _failed == 0 ? 0 : 1;
    }
}
'''


def _log(names: list[str], failed: list[str] | None = None, summary: bool = True) -> str:
    failed = failed or []
    body = ["  pass  %s" % n for n in names] + [
        "  FAIL  %s  --  detail" % n for n in failed
    ]
    if summary:
        body.append(
            "--- %d passed, %d failed, of %d case(s) ---"
            % (len(names), len(failed), len(names) + len(failed))
        )
    return "\n".join(body) + "\n"


_GOOD_NAMES = [
    "alpha holds",
    "beta holds",
    "row carries: 'ONE'",
    "row carries: 'TWO'",
    "row carries: 'THREE'",
    "CONTROL: gamma does not",
]


def self_test() -> int:
    """Arms, positive control FIRST.

    ⛔ EVERY NEGATIVE ARM IS DRIVEN AGAINST THE SAME INSTRUMENT THE GATE USES --
    `findings()` itself, never a re-implementation beside it. An arm that built
    its own answer would agree with a broken parser.
    """
    arms: list[tuple[str, bool, str]] = []

    def arm(name: str, ok: bool, detail: str = "") -> None:
        arms.append((name, ok, detail))

    # 1. POSITIVE CONTROL, and it asserts the derivation did WORK rather than
    #    merely returning no findings: a parser that matched nothing would also
    #    produce an empty finding list against any log at all.
    try:
        exact, loops = declaration(_GOOD_SOURCE)
        arm("positive: exact anchors derived", len(exact) == 3, "got %r" % (exact,))
        arm("positive: one data-driven family of 3",
            len(loops) == 1 and loops[0][1] == 3, "got %r" % (loops,))
        arm("positive: a well-formed log yields no finding",
            findings(_GOOD_SOURCE, _log(_GOOD_NAMES)) == [], "")
    except Refusal as exc:
        arm("positive: the good source parses", False, str(exc))

    # 2. THE OVER-MATCH ARM. `Check(name, ...)` in the `Eq` helper's body sits at
    #    the same indent as a real declaration. If it were counted, the gate would
    #    demand a case literally named `name` and red on every honest run.
    try:
        arm("helper-body: the Eq forwarder is not a declaration",
            "name" not in declaration(_GOOD_SOURCE)[0], "")
    except Refusal as exc:
        arm("helper-body", False, str(exc))

    # 3. A named case stops running -- the gate must NAME it.
    short = [n for n in _GOOD_NAMES if n != "CONTROL: gamma does not"]
    f = findings(_GOOD_SOURCE, _log(short))
    arm("missing-case: a dropped case is a finding",
        any("CONTROL: gamma does not" in s for s in f), "got %r" % (f,))

    # 4. THE ARM THE OLD FLOOR COULD NOT HAVE: the data-driven family shrinks
    #    while every remaining case passes.
    short2 = [n for n in _GOOD_NAMES if n != "row carries: 'TWO'"]
    f = findings(_GOOD_SOURCE, _log(short2))
    arm("loop-shrank: a data-driven case stopping is a finding",
        any("data-driven family" in s for s in f), "got %r" % (f,))

    # 5. ⭐ THE ARM THE REAL ARTIFACT TAUGHT ME. A family whose rows produce
    #    COLLIDING case names must still be counted by EXECUTIONS. The first cut
    #    used a set and under-counted the live suite's 11-row family as 9,
    #    because three of its rows share a first token. Two arms, because the
    #    fix must hold in both directions: the full family passes, and a short
    #    one still reds even though its distinct-name count is unchanged.
    collide = ["alpha holds", "beta holds", "CONTROL: gamma does not",
               "row carries: 'ONE'", "row carries: 'ONE'", "row carries: 'ONE'"]
    arm("name-collision: 3 executions of one name satisfy a 3-row family",
        findings(_GOOD_SOURCE, _log(collide)) == [],
        "got %r" % (findings(_GOOD_SOURCE, _log(collide)),))
    short3 = collide[:-1]
    f = findings(_GOOD_SOURCE, _log(short3))
    arm("name-collision: losing one of the colliding rows still reds",
        any("data-driven family" in s for s in f), "got %r" % (f,))

    # 6. ...and the SAME log passes a floor of the kind this gate replaces,
    #    which is why the floor is being replaced. Driven, not asserted.
    arm("loop-shrank: a floor would have passed that same log",
        len(short2) >= 5, "the floor arm must use a log above the floor")

    # 7. THE TWO HALVES OF THE "LOOP THAT DECLARES NOTHING" RULE. A setup loop
    #    must be ignored (refusing on one is a false red, and a false red gets a
    #    gate weakened); a loop whose case declarations this parser cannot read
    #    must refuse. The difference is measured from the body, not assumed.
    setup = _GOOD_SOURCE.replace(
        "        foreach (var row in new[] {",
        "        foreach (var warm in new[] {\n            \"A\",\n        })\n"
        "        {\n            Sink(warm);\n        }\n\n"
        "        foreach (var row in new[] {",
    )
    try:
        ex, lp = declaration(setup)
        arm("setup-loop: a loop declaring no case is ignored, not refused",
            len(lp) == 1 and lp[0][1] == 3, "got %r" % (lp,))
        arm("setup-loop: ...and the good log still passes",
            findings(setup, _log(_GOOD_NAMES)) == [], "")
    except Refusal as exc:
        arm("setup-loop: ignored not refused", False, str(exc))

    # 8. ⭐ THE PLURAL IN THIS GATE'S OWN CLAIM. It says "each data-driven
    #    family" and every arm above has exactly ONE, so the plural was an
    #    untested assertion -- the shape this repo calls "a first witness does
    #    not witness parameters". Two families, and the SECOND one shrinking must
    #    red on its own, or a second family could be added later and silently
    #    require nothing.
    two = _GOOD_SOURCE.replace(
        '        Check("CONTROL: gamma does not", false == false, "");',
        '''        foreach (var w in new[] {
            "P one",
            "Q two",
        })
        {
            Eq($"second family: \'{w.Split(\' \')[0]}\'", "y", "y");
        }

        Check("CONTROL: gamma does not", false == false, "");''')
    try:
        _ex, lps = declaration(two)
        arm("two-families: both are derived", len(lps) == 2, "got %r" % (lps,))
        both = _GOOD_NAMES + ["second family: 'P'", "second family: 'Q'"]
        arm("two-families: a complete log passes",
            findings(two, _log(both)) == [], "got %r" % (findings(two, _log(both)),))
        f2 = findings(two, _log(both[:-1]))
        arm("two-families: the SECOND family shrinking reds by name",
            any("second family" in s for s in f2), "got %r" % (f2,))
    except Refusal as exc:
        arm("two-families", False, str(exc))

    # 9. Refusals -- each one a shape that must not read as success.
    for label, src, lg, needle in [
        ("no-summary", _GOOD_SOURCE, _log(_GOOD_NAMES, summary=False), "summary"),
        ("empty-log", _GOOD_SOURCE, "", "summary"),
        ("no-anchors", "static class P { }\n", _log(_GOOD_NAMES), "derive its subject"),
        (
            "unbounded-shape",
            _GOOD_SOURCE.replace(
                '        Check("CONTROL: gamma does not", false == false, "");',
                '        Eq($"floating {x} case", "a", "a");',
            ),
            _log(_GOOD_NAMES),
            "cannot be bounded",
        ),
        (
            "empty-family",
            _GOOD_SOURCE.replace('            "ONE first",\n', "")
            .replace('            "TWO second",\n', "")
            .replace('            "THREE third",\n', ""),
            _log(_GOOD_NAMES),
            "EMPTY data set",
        ),
        (
            "unreadable-family",
            _GOOD_SOURCE.replace(
                "            Eq($\"row carries: '{row.Split(' ')[0]}'\", \"x\", \"x\");",
                "            Eq(NameFor(row), \"x\", \"x\");",
            ),
            _log(_GOOD_NAMES),
            "cannot read",
        ),
        (
            "duplicate-name",
            _GOOD_SOURCE.replace(
                '        Check("beta holds", true, "");',
                '        Check("alpha holds", true, "");',
            ),
            _log(_GOOD_NAMES),
            "more than once",
        ),
    ]:
        try:
            findings(src, lg)
            arm("refusal/%s" % label, False, "returned instead of refusing")
        except Refusal as exc:
            arm("refusal/%s" % label, needle in str(exc), "said %r" % str(exc)[:80])

    # 10. A zero-case summary is a refusal, not a pass.
    try:
        findings(_GOOD_SOURCE, "--- 0 passed, 0 failed, of 0 case(s) ---\n")
        arm("refusal/zero-cases", False, "returned instead of refusing")
    except Refusal as exc:
        arm("refusal/zero-cases", "examined nothing" in str(exc), str(exc)[:80])

    # 11. A failing case is a finding that names it.
    f = findings(_GOOD_SOURCE, _log(_GOOD_NAMES, failed=["beta holds"]))
    arm("failed-case: a FAIL row is named",
        any("case FAILED: beta holds" in s for s in f), "got %r" % (f,))

    # 12. THE REAL ARTIFACT. Run the derivation on the file this gate actually
    #    guards -- a parser tuned on a fixture and never pointed at production is
    #    the census-filter error this repo has already paid for once.
    if DEFAULT_SOURCE.exists():
        try:
            exact, loops = declaration(DEFAULT_SOURCE.read_text(encoding="utf-8"))
            arm("real-source: declares named cases", len(exact) >= 2,
                "got %d" % len(exact))
            arm("real-source: declares at least one data-driven family",
                len(loops) >= 1, "got %d" % len(loops))
            arm("real-source: no case name is empty",
                all(n.strip() for n in exact), "")
        except Refusal as exc:
            arm("real-source parses", False, str(exc))
    else:
        arm("real-source: present", False,
            "%s is missing" % DEFAULT_SOURCE.as_posix())

    bad = [(n, d) for n, ok, d in arms if not ok]
    for name, ok, detail in arms:
        print("  %s  %s%s" % ("pass" if ok else "FAIL", name,
                              "" if ok else "  --  %s" % detail))
    if bad:
        print("check_title_oracle_ran: SELF-TEST FAILED (%d of %d arm(s))"
              % (len(bad), len(arms)))
        return 1
    print("check_title_oracle_ran: SELF-TEST OK (%d arms)" % len(arms))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prove the title oracle's suite ran every case it declares."
    )
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--log", help="the suite's stdout to adjudicate")
    parser.add_argument("--source", default=DEFAULT_SOURCE.as_posix(),
                        help="the C# suite whose declaration is derived")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    if not args.log:
        print("check_title_oracle_ran: REFUSED -- --log is required (or "
              "--self-test)", file=sys.stderr)
        return 2

    source_path = pathlib.Path(args.source)
    if not source_path.is_file():
        print("check_title_oracle_ran: REFUSED -- the source %s does not exist, "
              "so no declaration can be derived" % source_path.as_posix(), file=sys.stderr)
        return 2
    log_path = pathlib.Path(args.log)
    if not log_path.is_file() or not log_path.read_text(
            encoding="utf-8", errors="replace").strip():
        print("check_title_oracle_ran: REFUSED -- the log %s is missing or empty, "
              "so nothing proves a case executed" % log_path.as_posix(), file=sys.stderr)
        return 2

    try:
        found = findings(
            source_path.read_text(encoding="utf-8"),
            log_path.read_text(encoding="utf-8", errors="replace"),
        )
    except Refusal as exc:
        print("check_title_oracle_ran: REFUSED -- %s" % exc, file=sys.stderr)
        return 2

    if found:
        for line in found:
            print("check_title_oracle_ran: %s" % line, file=sys.stderr)
        print("check_title_oracle_ran: FAILED (%d finding(s))" % len(found),
              file=sys.stderr)
        return 1

    exact, loops = declaration(source_path.read_text(encoding="utf-8"))
    total = len(exact) + sum(s for _p, s, _b in loops)
    print("check_title_oracle_ran: OK (%d declared case(s) each proved executed "
          "and passing by name: %d named + %d across %d data-driven famil%s)"
          % (total, len(exact), total - len(exact), len(loops),
             "y" if len(loops) == 1 else "ies"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
