(** Factory for creating tool instances from toolbar enum values. *)

let create_tool (tool : Toolbar.tool) : Canvas_tool.canvas_tool =
  match tool with
  | Toolbar.Selection -> (new Selection_tool.selection_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Direct_selection -> (new Selection_tool.direct_selection_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Group_selection -> (new Selection_tool.group_selection_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Line -> (new Drawing_tool.line_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Rect -> (new Drawing_tool.rect_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Rounded_rect -> (new Drawing_tool.rounded_rect_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Polygon -> (new Drawing_tool.polygon_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Star -> (new Drawing_tool.star_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Pen -> (new Pen_tool.pen_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Add_anchor_point -> (new Add_anchor_point_tool.add_anchor_point_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Delete_anchor_point -> (new Delete_anchor_point_tool.delete_anchor_point_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Pencil -> (new Pencil_tool.pencil_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Path_eraser -> (new Path_eraser_tool.path_eraser_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Smooth -> (new Smooth_tool.smooth_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Type_tool -> (new Type_tool.type_tool :> Canvas_tool.canvas_tool)
  | Toolbar.Type_on_path -> (new Type_on_path_tool.type_on_path_tool :> Canvas_tool.canvas_tool)
