# OCaml Jas Library
#
# Built using Dune build system integrated with Bazel.

filegroup(
    name = "lib_files",
    srcs = [
        "canvas.ml",
        "canvas_subwindow.ml",
        "dune",
        "toolbar.ml",
    ],
    visibility = ["//jas_ocaml:__subpackages__"],
)
